# -*- coding: utf-8 -*-
"""Day_21_Penguin_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7KnaHhYATE0jCdqwfvGqwOw0STDVJSf
"""

#Penguin dataset bp task

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("penguins")
df

#KPI 1 — Total Penguins
total_penguins = len(df)
total_penguins

#KPI 2 — Species Distribution
species_count = df['species'].value_counts()
species_percentage = df['species'].value_counts(normalize=True) * 100
print(species_count)
print(species_percentage)

#KPI 3 — Island Distribution
island_count = df['island'].value_counts()
island_percentage = df['island'].value_counts(normalize=True) * 100
print(island_count)
print(island_percentage)

#KPI 4 — Average Body Mass
overall_average_bodymass = df['body_mass_g'].mean()
bodymass_species = df.groupby("species")['body_mass_g'].mean()
bodymass_gender = df.groupby("sex")['body_mass_g'].mean()
print(overall_average_bodymass)
print(bodymass_species)
print(bodymass_gender)

#KPI 5 — Average Flipper Length
overall_average_flipperlength = df['flipper_length_mm'].mean()
average_species_flipper = df.groupby("species")['flipper_length_mm'].mean()
average_gender_flipper = df.groupby("sex")['flipper_length_mm'].mean()
print(overall_average_flipperlength)
print(average_species_flipper)
print(average_gender_flipper)

#KPI 6 — Average Bill Length
overall_average_billlength = df['bill_length_mm'].mean()
average_species_billlength = df.groupby("species")['bill_length_mm'].mean()
print(overall_average_billlength)
print(average_species_billlength)

#KPI 7 — Average Bill Depth
overall_average_billdepth = df['bill_depth_mm'].mean()
average_species_billdepth = df.groupby("species")['bill_depth_mm'].mean()
print(overall_average_billdepth)
print(average_species_billdepth)

#KPI 8 — Bill Ratio
df['bill_ratio'] = df['bill_length_mm'] / df['bill_depth_mm']
average_ratio_species = df.groupby('species')['bill_ratio'].mean()
average_ratio_species

#KPI 9 — Male vs Female
gender_count = df['sex'].value_counts()
gender_percentage = df['sex'].value_counts(normalize=True) * 100
print(gender_count)
print(gender_percentage)

#KPI 10 — Gender Size Difference
bodymass_gender = df.groupby("sex")['body_mass_g'].mean()
average_gender_flipper = df.groupby("sex")['flipper_length_mm'].mean()
bodymass_gender
average_gender_flipper

#KPI 11 — Correlation Matrix
correlation_matrix = df.corr(numeric_only=True)
correlation_matrix

#KPI 12 - Highest Correlation Pair
corr_pairs = correlation_matrix.unstack()
corr_pairs = corr_pairs.sort_values(ascending=False)
corr_pairs[1:10]

#KPI 13 — Species per Island
species_island = pd.crosstab(df['island'], df['species'])
species_island

#KPI 14 — Avg Body Mass per Island
df.groupby('island')['body_mass_g'].mean()

#KPI 15 — Avg Flipper Length per Island
df.groupby('island')['flipper_length_mm'].mean()

#KPI 16 — Missing Percentage
missing_percentage = df.isnull().sum() / len(df) * 100
missing_percentage

#KPI 17 - Outlier detection

#Body Mass Outliers
Q1 = df['body_mass_g'].quantile(0.25)
Q3 = df['body_mass_g'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR


body_mass_outliers = df[(df['body_mass_g'] < lower_bound) | (df['body_mass_g'] > upper_bound)]

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

print("Body Mass Outliers:")
print(body_mass_outliers)
print("Number of Body Mass Outliers:", len(body_mass_outliers))

#Flipper Length Outliers
Q1 = df['flipper_length_mm'].quantile(0.25)
Q3 = df['flipper_length_mm'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

flipper_outliers = df[(df['flipper_length_mm'] < lower_bound) | (df['flipper_length_mm'] > upper_bound)]

print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

print("Flipper Length Outliers:")
print(flipper_outliers)
print("Number of Flipper Length Outliers:", len(flipper_outliers))

# CHART REQUIREMENTS

# 1.Species Distribution Bar Chart
species_count = df['species'].value_counts()
plt.figure(figsize=(6,4))
sns.barplot(x=species_count.index, y=species_count.values)
plt.xlabel("Species")
plt.ylabel("Count")
plt.title("Species Distribution")
plt.show()

# 2.Island Distribution
island_count = df['island'].value_counts()
plt.figure(figsize=(6,4))
sns.barplot(x=island_count.index, y=island_count.values)
plt.xlabel("Island")
plt.ylabel("Count")
plt.title("Island Distribution")
plt.show()

#3.Gender Distribution
gender_count = df['sex'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(
    gender_count.values,
    labels=gender_count.index,
    autopct='%1.1f%%',
    startangle=90
)
plt.title("Gender Distribution")
plt.show()

# 4. Body Mass Distribution (Histogram)

plt.figure(figsize=(6,4))
sns.histplot(df['body_mass_g'], bins=20, kde=True)
plt.xlabel("Body Mass (g)")
plt.ylabel("Frequency")
plt.title("Body Mass Distribution")
plt.show()

# 5. Flipper Length Distribution (Histogram)

plt.figure(figsize=(6,4))
sns.histplot(df['flipper_length_mm'], bins=20, kde=True)
plt.xlabel("Flipper Length (mm)")
plt.ylabel("Frequency")
plt.title("Flipper Length Distribution")
plt.show()

# 6. Bill Length Distribution (Histogram)

plt.figure(figsize=(6,4))
sns.histplot(df['bill_length_mm'], bins=20, kde=True)
plt.xlabel("Bill Length (mm)")
plt.ylabel("Frequency")
plt.title("Bill Length Distribution")
plt.show()

# 7. Average Body Mass by Species (Bar Chart)

plt.figure(figsize=(6,4))
sns.barplot(x='species', y='body_mass_g', data=df)
plt.xlabel("Species")
plt.ylabel("Average Body Mass (g)")
plt.title("Average Body Mass by Species")
plt.show()

# 8. Average Flipper Length by Species (Bar Chart)

plt.figure(figsize=(6,4))
sns.barplot(x='species', y='flipper_length_mm', data=df)
plt.xlabel("Species")
plt.ylabel("Average Flipper Length (mm)")
plt.title("Average Flipper Length by Species")
plt.show()

# 9. Average Body Mass by Gender (Bar Chart)

plt.figure(figsize=(6,4))
sns.barplot(x='sex', y='body_mass_g', data=df)
plt.xlabel("Gender")
plt.ylabel("Average Body Mass (g)")
plt.title("Average Body Mass by Gender")
plt.show()

# 10. Species Distribution by Island (Stacked Bar Chart)

species_island = pd.crosstab(df['island'], df['species'])
species_island.plot(kind='bar', stacked=True, figsize=(7,5))
plt.xlabel("Island")
plt.ylabel("Count")
plt.title("Species Distribution by Island")
plt.legend(title="Species")
plt.show()

# 11. Flipper Length vs Body Mass (Scatter Plot)

plt.figure(figsize=(7,5))
sns.scatterplot(
    x='flipper_length_mm',
    y='body_mass_g',
    hue='species',
    size='bill_length_mm',
    data=df
)
plt.xlabel("Flipper Length (mm)")
plt.ylabel("Body Mass (g)")
plt.title("Flipper Length vs Body Mass")
plt.legend()
plt.show()

# 12. Bill Length vs Bill Depth (Scatter Plot)

plt.figure(figsize=(7,5))
sns.scatterplot(
    x='bill_length_mm',
    y='bill_depth_mm',
    hue='species',
    data=df
)
plt.xlabel("Bill Length (mm)")
plt.ylabel("Bill Depth (mm)")
plt.title("Bill Length vs Bill Depth")
plt.show()

# 13. Correlation Heatmap

plt.figure(figsize=(7,5))
correlation_matrix = df.corr(numeric_only=True)
sns.heatmap(
    correlation_matrix,
    annot=True,
    cmap="coolwarm",
    fmt=".2f"
)
plt.title("Correlation Heatmap")
plt.show()

# Executive Dashboard

# Install libraries (run once)
!pip install seaborn plotly ipywidgets

import pandas as pd
import seaborn as sns
import plotly.express as px
import ipywidgets as widgets
from IPython.display import display

# Load penguin dataset
df = sns.load_dataset("penguins")

# Remove missing values (important for charts)
df = df.dropna()

df.head()

species_filter = widgets.SelectMultiple(
    options=sorted(df['species'].unique()),
    description='Species'
)

island_filter = widgets.SelectMultiple(
    options=sorted(df['island'].unique()),
    description='Island'
)

gender_filter = widgets.SelectMultiple(
    options=sorted(df['sex'].unique()),
    description='Gender'
)

def dashboard(species, island, gender):

    filtered_df = df.copy()

    if species:
        filtered_df = filtered_df[filtered_df['species'].isin(species)]

    if island:
        filtered_df = filtered_df[filtered_df['island'].isin(island)]

    if gender:
        filtered_df = filtered_df[filtered_df['sex'].isin(gender)]

    # KPI
    total_penguins = len(filtered_df)
    avg_body_mass = filtered_df['body_mass_g'].mean()
    avg_flipper = filtered_df['flipper_length_mm'].mean()
    avg_bill = filtered_df['bill_length_mm'].mean()

    gender_percent = filtered_df['sex'].value_counts(normalize=True) * 100

    print("===== KPI SUMMARY =====")
    print("Total Penguins:", total_penguins)
    print("Avg Body Mass:", round(avg_body_mass,2))
    print("Avg Flipper Length:", round(avg_flipper,2))
    print("Avg Bill Length:", round(avg_bill,2))

    male = gender_percent.get('Male',0)
    female = gender_percent.get('Female',0)

    print("Male %:", round(male,2))
    print("Female %:", round(female,2))


    # -----------------------
    # Distribution Chart
    # -----------------------
    plt.figure(figsize=(6,4))
    sns.histplot(filtered_df['body_mass_g'], bins=20)
    plt.title("Body Mass Distribution")
    plt.show()


    # -----------------------
    # Comparison Chart
    # -----------------------
    plt.figure(figsize=(6,4))
    sns.barplot(x='species', y='body_mass_g', data=filtered_df)
    plt.title("Average Body Mass by Species")
    plt.show()


    # -----------------------
    # Relationship Chart
    # -----------------------
    plt.figure(figsize=(6,4))
    sns.scatterplot(x='flipper_length_mm',
                    y='body_mass_g',
                    hue='species',
                    data=filtered_df)
    plt.title("Flipper Length vs Body Mass")
    plt.show()


    # -----------------------
    # Correlation Heatmap
    # -----------------------
    plt.figure(figsize=(6,4))
    corr = filtered_df.corr(numeric_only=True)
    sns.heatmap(corr, annot=True, cmap="coolwarm")
    plt.title("Correlation Heatmap")
    plt.show()

species_filter = widgets.SelectMultiple(
    options=sorted(df['species'].unique()),
    description='Species'
)

island_filter = widgets.SelectMultiple(
    options=sorted(df['island'].unique()),
    description='Island'
)

gender_filter = widgets.SelectMultiple(
    options=sorted(df['sex'].unique()),
    description='Gender'
)

ui = widgets.VBox([
    species_filter,
    island_filter,
    gender_filter
])

out = widgets.interactive_output(
    dashboard,
    {
        'species': species_filter,
        'island': island_filter,
        'gender': gender_filter
    }
)

display(ui, out)