# -*- coding: utf-8 -*-
"""Day_22_AutoMPG_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7KnaHhYATE0jCdqwfvGqwOw0STDVJSf
"""

#Auto mpg bp task

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

columns = [
    "mpg","cylinders","displacement","horsepower",
    "weight","acceleration","model_year","origin","car_name"
]

df = pd.read_csv("/content/auto-mpg.data",
                 names=columns,
                 delim_whitespace=True)

df.head()

# Replace missing values

df['horsepower'] = df['horsepower'].replace('?', np.nan)

df['horsepower'] = df['horsepower'].astype(float)

df = df.dropna()

# Dataset info

df.info()

df.describe()

df.shape

#Executive-Level KPIs (High Priority)
avg_mpg = df['mpg'].mean()

max_mpg = df['mpg'].max()

min_mpg = df['mpg'].min()

total_vehicles = len(df)

avg_hp = df['horsepower'].mean()

avg_disp = df['displacement'].mean()

avg_cyl = df['cylinders'].mean()

print("Average MPG:", avg_mpg)
print("Max MPG:", max_mpg)
print("Min MPG:", min_mpg)
print("Total Vehicles:", total_vehicles)
print("Average Horsepower:", avg_hp)

# ================================
# Regional KPI Analysis
# ================================

# Convert origin codes to region names
df['origin'] = df['origin'].replace({
    1: "USA",
    2: "Europe",
    3: "Japan"
})

# Calculate KPIs
avg_mpg_origin = df.groupby('origin')['mpg'].mean()
vehicle_count_origin = df['origin'].value_counts()
market_share_origin = (df['origin'].value_counts() / len(df)) * 100
avg_hp_origin = df.groupby('origin')['horsepower'].mean()

# Combine all KPIs into one table
regional_kpi = pd.DataFrame({
    "Average MPG": avg_mpg_origin,
    "Vehicle Count": vehicle_count_origin,
    "Market Share %": market_share_origin,
    "Average Horsepower": avg_hp_origin
})

# Round values for better display
regional_kpi = regional_kpi.round(2)

print("===== Regional Performance KPIs =====")

regional_kpi

# ================================
# Engine Performance KPIs
# ================================

# Create Power-to-Weight Ratio column
df['power_to_weight'] = df['horsepower'] / df['weight']

# Calculate KPIs
avg_hp = df['horsepower'].mean()
avg_disp = df['displacement'].mean()
avg_cyl = df['cylinders'].mean()
avg_pw_ratio = df['power_to_weight'].mean()

# Create KPI table
engine_kpi = pd.DataFrame({
    "KPI": [
        "Average Horsepower",
        "Average Displacement",
        "Average Cylinders",
        "Power-to-Weight Ratio"
    ],

    "Value": [
        round(avg_hp,2),
        round(avg_disp,2),
        round(avg_cyl,2),
        round(avg_pw_ratio,5)
    ],

    "Business Insight": [
        "Engine strength level",
        "Engine size trend",
        "Engine configuration trend",
        "Performance efficiency"
    ]
})

print("===== Engine Performance KPIs =====")

engine_kpi

# =====================================
# Correlation & Engineering KPIs
# =====================================

# 1 MPG vs Weight Correlation
mpg_weight_corr = df['mpg'].corr(df['weight'])

# 2 MPG vs Horsepower Correlation
mpg_hp_corr = df['mpg'].corr(df['horsepower'])

# 3 MPG by Cylinders
mpg_by_cylinders = df.groupby('cylinders')['mpg'].mean()

# 4 Weight Trend by Year
weight_trend = df.groupby('model_year')['weight'].mean()

# Create KPI table
correlation_kpi = pd.DataFrame({
    "KPI": [
        "MPG vs Weight Correlation",
        "MPG vs Horsepower Correlation",
        "MPG by Cylinders",
        "Weight Trend by Year"
    ],

    "Value": [
        round(mpg_weight_corr,3),
        round(mpg_hp_corr,3),
        "See chart below",
        "See chart below"
    ],

    "Purpose": [
        "Impact of vehicle mass on efficiency",
        "Power vs fuel trade-off",
        "Effect of engine size on fuel economy",
        "Lightweight strategy progress"
    ]
})

print("===== Correlation & Engineering KPIs =====")

correlation_kpi

# 1 Fuel Efficiency Trend
# Calculate average MPG per year
mpg_trend = df.groupby('model_year')['mpg'].mean()

plt.figure(figsize=(8,5))
plt.plot(mpg_trend.index, mpg_trend.values, marker='o')
plt.title("Fuel Efficiency Trend Over Years")
plt.xlabel("Model Year")
plt.ylabel("Average MPG")
plt.grid(True)
plt.show()

# 2 MPG by Origin (Seaborn)

plt.figure(figsize=(7,5))

sns.barplot(x='origin', y='mpg', data=df)

plt.title("Average MPG by Origin")

plt.xlabel("Origin")

plt.ylabel("Average MPG")

plt.show()

# 3 Market Share by Origin
origin_counts = df['origin'].value_counts()
plt.figure(figsize=(6,6))
plt.pie(
    origin_counts,
    labels=origin_counts.index,
    autopct='%1.1f%%'
)
plt.title("Market Share by Origin")
plt.show()

# 4 MPG vs Weight
plt.figure(figsize=(7,5))
sns.regplot(
    x='weight',
    y='mpg',
    data=df
)
plt.title("MPG vs Vehicle Weight")
plt.xlabel("Vehicle Weight")
plt.ylabel("MPG")
plt.show()

# 5 MPG vs Horsepower

plt.figure(figsize=(7,5))
sns.scatterplot(
    x='horsepower',
    y='mpg',
    data=df
)
plt.title("MPG vs Horsepower")
plt.xlabel("Horsepower")
plt.ylabel("MPG")
plt.show()

# 6 Engine Distribution
plt.figure(figsize=(7,5))
sns.countplot(
    x='cylinders',
    data=df
)
plt.title("Engine Distribution by Cylinders")
plt.xlabel("Number of Cylinders")
plt.ylabel("Vehicle Count")
plt.show()

# 7 MPG Distribution

plt.figure(figsize=(7,5))
sns.histplot(
    df['mpg'],
    bins=20
)
plt.title("MPG Distribution")
plt.xlabel("Miles Per Gallon (MPG)")
plt.ylabel("Frequency")
plt.show()

# 8 Correlation Matrix

# Select relevant variables
corr_data = df[['mpg','weight','horsepower','displacement','cylinders','acceleration']]
# Compute correlation matrix
corr_matrix = corr_data.corr()
# Plot heatmap
plt.figure(figsize=(8,6))
sns.heatmap(
    corr_matrix,
    annot=True,
    cmap='coolwarm'
)
plt.title("Correlation Matrix of Vehicle Features")
plt.show()

# AUTO MPG EXECUTIVE DASHBOARD

import matplotlib.pyplot as plt
import seaborn as sns

# KPI CALCULATIONS
avg_mpg = df['mpg'].mean()
avg_hp = df['horsepower'].mean()
total_vehicles = len(df)
mpg_trend = df.groupby('model_year')['mpg'].mean()
yoy_growth = ((mpg_trend.iloc[-1] - mpg_trend.iloc[0]) / mpg_trend.iloc[0]) * 100


print("=================================")
print("        EXECUTIVE DASHBOARD      ")
print("=================================")

print("Average MPG:", round(avg_mpg,2))

print("YoY MPG Growth (%):", round(yoy_growth,2))

print("Average Horsepower:", round(avg_hp,2))

print("Total Vehicles:", total_vehicles)

# CREATE DASHBOARD LAYOUT
fig, axes = plt.subplots(2,3, figsize=(18,10))
fig.suptitle("Auto MPG Dashboard", fontsize=20)


# 1 Fuel Efficiency Trend
sns.lineplot(
    x='model_year',
    y='mpg',
    data=df,
    marker='o',
    ax=axes[0,0]
)
axes[0,0].set_title("Fuel Efficiency Trend")
axes[0,0].set_xlabel("Model Year")
axes[0,0].set_ylabel("Average MPG")

# 2 MPG by Origin
sns.barplot(
    x='origin',
    y='mpg',
    data=df,
    ax=axes[0,1]
)
axes[0,1].set_title("Average MPG by Origin")

# 3 MPG vs Weight
sns.regplot(
    x='weight',
    y='mpg',
    data=df,
    ax=axes[0,2]
)
axes[0,2].set_title("MPG vs Weight")

# 4 MPG vs Horsepower
sns.regplot(
    x='horsepower',
    y='mpg',
    data=df,
    ax=axes[1,0]
)
axes[1,0].set_title("MPG vs Horsepower")

# 5 MPG Distribution
sns.histplot(
    df['mpg'],
    bins=20,
    kde=True,
    ax=axes[1,1]
)
axes[1,1].set_title("MPG Distribution")


# Empty space (for cleaner layout)
axes[1,2].axis('off')
plt.tight_layout()
plt.show()