# -*- coding: utf-8 -*-
"""pizza_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7KnaHhYATE0jCdqwfvGqwOw0STDVJSf
"""

# Pizza Sales Interactive Dashboard
# Based on pizza_sales_analysis notebook
# Tools: Python, Dash, Plotly, Pandas
# Feature: Click any chart to filter all other charts and KPIs

import dash
from dash import dcc, html, Input, Output, callback_context
import plotly.graph_objects as go
import pandas as pd

# Load and Prepare Data

df = pd.read_csv(r"C:\Users\hp\OneDrive\Desktop\INTERNSHIP_TIS\TASKS\WEEK07\pizza_sales.csv")
df['order_date'] = pd.to_datetime(df['order_date'], format='%d-%m-%Y')
df['day_of_week'] = df['order_date'].dt.day_name()
df['month_name']  = df['order_date'].dt.month_name()
df['month_num']   = df['order_date'].dt.month

# Shorten pizza name for display in small 3-column charts
def short_name(name):
    name = name.replace('The ', '').replace(' Pizza', '')
    return name

# Fixed orders
order_of_days   = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"]
order_of_months = ["January", "February", "March", "April", "May", "June",
                   "July", "August", "September", "October", "November", "December"]

pastel_colors  = ['#AEC6CF', '#FFD1DC', '#B5EAD7', '#FFDAC1']
pastel_colors2 = ['#AEC6CF', '#FFD1DC', '#B5EAD7', '#FFDAC1', '#C9C0D3']
blues          = ['#08519c', '#3182bd', '#6baed6', '#bdd7e7']

# App setup
app = dash.Dash(__name__)
app.title = "Pizza Sales Dashboard"

chart_box = {'border': '1px solid #ccc', 'borderRadius': '6px', 'overflow': 'hidden'}

# KPI card with emoji icon - now uses id for dynamic update
def kpi_card(icon, label, card_id):
    return html.Div(
        style={
            'backgroundColor': '#f2f2f2',
            'border': '1px solid #ddd',
            'borderRadius': '6px',
            'padding': '15px 20px',
            'textAlign': 'center',
            'minWidth': '155px'
        },
        children=[
            html.P(icon,  style={'margin': '0', 'fontSize': '28px'}),
            html.P(label, style={'margin': '4px 0 0 0', 'fontSize': '13px', 'color': 'gray'}),
            html.H3(id=card_id, style={'margin': '4px 0 0 0', 'color': '#222'})
        ]
    )

# Layout
app.layout = html.Div(
    style={'fontFamily': 'Arial, sans-serif', 'padding': '20px', 'backgroundColor': '#ffffff'},
    children=[

        # Title
        html.H2('Pizza Sales Interactive Dashboard',
                style={'textAlign': 'center', 'color': '#222', 'marginBottom': '4px'}),
        html.P('Sales Data Analysis - Year 2015',
               style={'textAlign': 'center', 'color': 'gray', 'marginBottom': '10px'}),

        # Reset button
        html.Div(
            html.Button('Reset Filters', id='reset-btn', n_clicks=0,
                        style={'padding': '8px 20px', 'backgroundColor': '#e74c3c',
                               'color': 'white', 'border': 'none', 'borderRadius': '5px',
                               'cursor': 'pointer', 'fontSize': '13px'}),
            style={'textAlign': 'center', 'marginBottom': '24px'}
        ),

        # KPI Cards
        html.Div(
            style={'display': 'flex', 'gap': '15px', 'justifyContent': 'center',
                   'flexWrap': 'wrap', 'marginBottom': '28px'},
            children=[
                kpi_card('💰', 'Total Revenue',       'kpi-revenue'),
                kpi_card('🛒', 'Total Orders',         'kpi-orders'),
                kpi_card('🍕', 'Total Pizzas Sold',    'kpi-pizzas'),
                kpi_card('📊', 'Average Order Value',  'kpi-avg-order'),
                kpi_card('🔢', 'Avg Pizzas Per Order', 'kpi-avg-pizza'),
            ]
        ),

        # Row 1 - Daily + Monthly
        html.Div(
            style={'display': 'grid', 'gridTemplateColumns': '1fr 1fr', 'gap': '20px', 'marginBottom': '20px'},
            children=[
                html.Div(dcc.Graph(id='chart-daily',   clickData=None), style=chart_box),
                html.Div(dcc.Graph(id='chart-monthly', clickData=None), style=chart_box),
            ]
        ),

        # Row 2 - Pie charts
        html.Div(
            style={'display': 'grid', 'gridTemplateColumns': '1fr 1fr', 'gap': '20px', 'marginBottom': '20px'},
            children=[
                html.Div(dcc.Graph(id='chart-pie-category', clickData=None), style=chart_box),
                html.Div(dcc.Graph(id='chart-pie-size',     clickData=None), style=chart_box),
            ]
        ),

        # Row 3 - Funnel full width
        html.Div(dcc.Graph(id='chart-funnel', clickData=None),
                 style={**chart_box, 'marginBottom': '20px'}),

        # Top 5
        html.H4('Top 5 Best Sellers', style={'color': 'green', 'marginBottom': '10px'}),
        html.Div(
            style={'display': 'grid', 'gridTemplateColumns': '1fr 1fr 1fr', 'gap': '15px', 'marginBottom': '20px'},
            children=[
                html.Div(dcc.Graph(id='chart-top5-revenue'),  style=chart_box),
                html.Div(dcc.Graph(id='chart-top5-quantity'), style=chart_box),
                html.Div(dcc.Graph(id='chart-top5-orders'),   style=chart_box),
            ]
        ),

        # Bottom 5
        html.H4('Bottom 5 Worst Sellers', style={'color': 'red', 'marginBottom': '10px'}),
        html.Div(
            style={'display': 'grid', 'gridTemplateColumns': '1fr 1fr 1fr', 'gap': '15px', 'marginBottom': '20px'},
            children=[
                html.Div(dcc.Graph(id='chart-bot5-revenue'),  style=chart_box),
                html.Div(dcc.Graph(id='chart-bot5-quantity'), style=chart_box),
                html.Div(dcc.Graph(id='chart-bot5-orders'),   style=chart_box),
            ]
        ),
    ]
)


# Helper: build all figures from a filtered dataframe
def build_figures(fdf):

    # KPIs
    total_revenue            = fdf['total_price'].sum()
    total_orders             = fdf['order_id'].nunique()
    total_pizzas_sold        = fdf['quantity'].sum()
    average_order_value      = total_revenue / total_orders if total_orders else 0
    average_pizzas_per_order = total_pizzas_sold / total_orders if total_orders else 0

    # Chart 1 - Daily Bar
    daily = fdf.groupby('day_of_week')['order_id'].nunique().reindex(order_of_days).fillna(0).reset_index()
    daily.columns = ['Day', 'Orders']
    fig_daily = go.Figure(go.Bar(
        x=daily['Day'], y=daily['Orders'],
        marker_color='skyblue', text=daily['Orders'], textposition='outside'
    ))
    fig_daily.update_layout(title='Total Orders by Day of the Week',
                            xaxis_title='Day of the Week', yaxis_title='Total Orders',
                            plot_bgcolor='white', paper_bgcolor='white',
                            yaxis=dict(gridcolor='lightgrey'))

    # Chart 2 - Monthly Line
    monthly = fdf.groupby('month_name')['order_id'].nunique().reindex(order_of_months).fillna(0).reset_index()
    monthly.columns = ['Month', 'Orders']
    fig_monthly = go.Figure(go.Scatter(
        x=monthly['Month'], y=monthly['Orders'],
        mode='lines+markers', line=dict(color='blue', width=2), marker=dict(size=8, color='blue')
    ))
    fig_monthly.update_layout(title='Monthly Trend of Total Orders',
                              xaxis_title='Month', yaxis_title='Total Orders',
                              xaxis_tickangle=-45, plot_bgcolor='white', paper_bgcolor='white',
                              yaxis=dict(gridcolor='lightgrey'))

    # Chart 3 - Pie Category
    cat_sales = fdf.groupby('pizza_category')['total_price'].sum().reset_index()
    cat_sales.columns = ['Category', 'Revenue']
    fig_pie_cat = go.Figure(go.Pie(
        labels=cat_sales['Category'], values=cat_sales['Revenue'],
        textinfo='label+percent', marker=dict(colors=pastel_colors)
    ))
    fig_pie_cat.update_layout(title='Percentage of Sales by Pizza Category', paper_bgcolor='white')

    # Chart 4 - Pie Size
    size_sales = fdf.groupby('pizza_size')['total_price'].sum().reset_index()
    size_sales.columns = ['Size', 'Revenue']
    fig_pie_size = go.Figure(go.Pie(
        labels=size_sales['Size'], values=size_sales['Revenue'],
        textinfo='label+percent', marker=dict(colors=pastel_colors2)
    ))
    fig_pie_size.update_layout(title='Percentage of Sales by Pizza Size', paper_bgcolor='white')

    # Chart 5 - Funnel
    cat_qty = fdf.groupby('pizza_category')['quantity'].sum().sort_values(ascending=False).reset_index()
    cat_qty.columns = ['Category', 'Quantity']
    fig_funnel = go.Figure(go.Funnel(
        y=cat_qty['Category'], x=cat_qty['Quantity'],
        marker=dict(color=blues[:len(cat_qty)]), textinfo='value+percent initial'
    ))
    fig_funnel.update_layout(title='Total Pizzas Sold by Pizza Category', paper_bgcolor='white')

    # Chart 6 - Top 5 Revenue
    t5r = fdf.groupby('pizza_name')['total_price'].sum().nlargest(5).sort_values().reset_index()
    t5r.columns = ['Pizza', 'Revenue']
    t5r['Label'] = t5r['Pizza'].apply(short_name)
    fig_t5r = go.Figure(go.Bar(
        y=t5r['Label'], x=t5r['Revenue'], orientation='h', marker_color='#2ca25f',
        text=t5r['Revenue'].apply(lambda x: f"${x:,.0f}"), textposition='outside'
    ))
    fig_t5r.update_layout(title='Top 5 Pizzas by Revenue', xaxis_title='Total Revenue',
                          plot_bgcolor='white', paper_bgcolor='white',
                          height=320, margin=dict(l=130, r=60, t=50, b=40),
                          xaxis=dict(gridcolor='lightgrey'))

    # Chart 6 - Top 5 Quantity
    t5q = fdf.groupby('pizza_name')['quantity'].sum().nlargest(5).sort_values().reset_index()
    t5q.columns = ['Pizza', 'Quantity']
    t5q['Label'] = t5q['Pizza'].apply(short_name)
    fig_t5q = go.Figure(go.Bar(
        y=t5q['Label'], x=t5q['Quantity'], orientation='h', marker_color='steelblue',
        text=t5q['Quantity'], textposition='outside'
    ))
    fig_t5q.update_layout(title='Top 5 Pizzas by Quantity Sold', xaxis_title='Total Quantity Sold',
                          plot_bgcolor='white', paper_bgcolor='white',
                          height=320, margin=dict(l=130, r=60, t=50, b=40),
                          xaxis=dict(gridcolor='lightgrey'))

    # Chart 6 - Top 5 Orders
    t5o = fdf.groupby('pizza_name')['order_id'].nunique().nlargest(5).sort_values().reset_index()
    t5o.columns = ['Pizza', 'Orders']
    t5o['Label'] = t5o['Pizza'].apply(short_name)
    fig_t5o = go.Figure(go.Bar(
        y=t5o['Label'], x=t5o['Orders'], orientation='h', marker_color='#74c476',
        text=t5o['Orders'], textposition='outside'
    ))
    fig_t5o.update_layout(title='Top 5 Pizzas by Total Orders', xaxis_title='Total Orders',
                          plot_bgcolor='white', paper_bgcolor='white',
                          height=320, margin=dict(l=130, r=60, t=50, b=40),
                          xaxis=dict(gridcolor='lightgrey'))

    # Chart 7 - Bottom 5 Revenue
    b5r = fdf.groupby('pizza_name')['total_price'].sum().nsmallest(5).sort_values(ascending=False).reset_index()
    b5r.columns = ['Pizza', 'Revenue']
    b5r['Label'] = b5r['Pizza'].apply(short_name)
    fig_b5r = go.Figure(go.Bar(
        y=b5r['Label'], x=b5r['Revenue'], orientation='h', marker_color='#cb181d',
        text=b5r['Revenue'].apply(lambda x: f"${x:,.0f}"), textposition='outside'
    ))
    fig_b5r.update_layout(title='Bottom 5 Pizzas by Revenue', xaxis_title='Total Revenue',
                          plot_bgcolor='white', paper_bgcolor='white',
                          height=320, margin=dict(l=130, r=60, t=50, b=40),
                          xaxis=dict(gridcolor='lightgrey'))

    # Chart 7 - Bottom 5 Quantity
    b5q = fdf.groupby('pizza_name')['quantity'].sum().nsmallest(5).sort_values(ascending=False).reset_index()
    b5q.columns = ['Pizza', 'Quantity']
    b5q['Label'] = b5q['Pizza'].apply(short_name)
    fig_b5q = go.Figure(go.Bar(
        y=b5q['Label'], x=b5q['Quantity'], orientation='h', marker_color='#9e9ac8',
        text=b5q['Quantity'], textposition='outside'
    ))
    fig_b5q.update_layout(title='Bottom 5 Pizzas by Quantity Sold', xaxis_title='Total Quantity Sold',
                          plot_bgcolor='white', paper_bgcolor='white',
                          height=320, margin=dict(l=130, r=60, t=50, b=40),
                          xaxis=dict(gridcolor='lightgrey'))

    # Chart 7 - Bottom 5 Orders
    b5o = fdf.groupby('pizza_name')['order_id'].nunique().nsmallest(5).sort_values(ascending=False).reset_index()
    b5o.columns = ['Pizza', 'Orders']
    b5o['Label'] = b5o['Pizza'].apply(short_name)
    fig_b5o = go.Figure(go.Bar(
        y=b5o['Label'], x=b5o['Orders'], orientation='h', marker_color='#fb6a4a',
        text=b5o['Orders'], textposition='outside'
    ))
    fig_b5o.update_layout(title='Bottom 5 Pizzas by Total Orders', xaxis_title='Total Orders',
                          plot_bgcolor='white', paper_bgcolor='white',
                          height=320, margin=dict(l=130, r=60, t=50, b=40),
                          xaxis=dict(gridcolor='lightgrey'))

    return (
        f"$ {total_revenue:,.2f}",
        f"{total_orders:,}",
        f"{total_pizzas_sold:,}",
        f"$ {average_order_value:.2f}",
        f"{average_pizzas_per_order:.2f}",
        fig_daily, fig_monthly, fig_pie_cat, fig_pie_size, fig_funnel,
        fig_t5r, fig_t5q, fig_t5o,
        fig_b5r, fig_b5q, fig_b5o
    )


# Main Callback - handles all click events and reset button
@app.callback(
    [
        Output('kpi-revenue',         'children'),
        Output('kpi-orders',          'children'),
        Output('kpi-pizzas',          'children'),
        Output('kpi-avg-order',       'children'),
        Output('kpi-avg-pizza',       'children'),
        Output('chart-daily',         'figure'),
        Output('chart-monthly',       'figure'),
        Output('chart-pie-category',  'figure'),
        Output('chart-pie-size',      'figure'),
        Output('chart-funnel',        'figure'),
        Output('chart-top5-revenue',  'figure'),
        Output('chart-top5-quantity', 'figure'),
        Output('chart-top5-orders',   'figure'),
        Output('chart-bot5-revenue',  'figure'),
        Output('chart-bot5-quantity', 'figure'),
        Output('chart-bot5-orders',   'figure'),
    ],
    [
        Input('chart-daily',         'clickData'),
        Input('chart-monthly',       'clickData'),
        Input('chart-pie-category',  'clickData'),
        Input('chart-pie-size',      'clickData'),
        Input('chart-funnel',        'clickData'),
        Input('reset-btn',           'n_clicks'),
    ]
)
def update_all(click_daily, click_monthly, click_pie_cat,
               click_pie_size, click_funnel, reset_clicks):

    ctx = callback_context
    if not ctx.triggered:
        return build_figures(df)

    triggered_id = ctx.triggered[0]['prop_id'].split('.')[0]

    if triggered_id == 'reset-btn':
        return build_figures(df)

    fdf = df.copy()

    if triggered_id == 'chart-daily' and click_daily:
        day = click_daily['points'][0]['x']
        fdf = fdf[fdf['day_of_week'] == day]

    elif triggered_id == 'chart-monthly' and click_monthly:
        month = click_monthly['points'][0]['x']
        fdf = fdf[fdf['month_name'] == month]

    elif triggered_id == 'chart-pie-category' and click_pie_cat:
        category = click_pie_cat['points'][0]['label']
        fdf = fdf[fdf['pizza_category'] == category]

    elif triggered_id == 'chart-pie-size' and click_pie_size:
        size = click_pie_size['points'][0]['label']
        fdf = fdf[fdf['pizza_size'] == size]

    elif triggered_id == 'chart-funnel' and click_funnel:
        category = click_funnel['points'][0]['y']
        fdf = fdf[fdf['pizza_category'] == category]

    return build_figures(fdf)


# Run App

if __name__ == '__main__':
    app.run(debug=False, use_reloader=False, port=8050)